# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06ae4212cc1171eb037f827b314247d3032ad7c92c057ba0139398619535bee6ee3889171e94a953ab35318186730fde05cd5f8851034e095d44117c50573299

test:
  secret_key_base: 3b7f6c480866d7131d48e6806c20330ea103be5cc6f6fbe5f6ee660093ad9ca9b04e610597a46dee8e1eb2fd84a390c3e25f996984d6071f62d2e7211de7e303

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c479703dfe8c57f54e0c09a43f892cf6835f0b7de265375ef30a762e681b969abc5bcab0ae423a3271e570f96fddbf0f425adb5add5a282b25e571b8ab519c36
